# Generated by Django 4.1.7 on 2023-03-26 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='has_used',
        ),
        migrations.AddField(
            model_name='promo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo',
            name='promocode',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
